namespace WasteHunters
{
    public static class RubbishPrices
    {
        public static Dictionary<string, int> RubbishValues { get; } = new Dictionary<string, int>
        {
            { "Used razor blades", 150 },
            { "Used batteries", 200 },
            { "Oil bottles", 180 },
            { "Fishing nets", 175 },
            { "Plastic bottles", 120 },
            { "Broken tools", 100 },
            { "Tire", 100 },
            { "Shattered glass", 95 },
            { "Empty glass jar of pesto", 90 },
            { "Not working computer mouse", 85 },
            { "Plastic wraps and boxes", 75 },
            { "Broken glass", 70 },
            { "Dirty rags", 65 },
            { "Empty aluminium cans", 60 },
            { "Bottle caps", 55 },
            { "Bubble gums", 50 },
            { "Empty can of animal food", 45 },
            { "Pair of socks with holes", 40 },
            { "Candy wrapper", 35 },
            { "Cigarette butts", 30 },
            { "Receipts and paper scraps", 25 },
            { "Empty roll of toilet paper", 20 },
            { "Egg shells", 15 },
            { "Rotten banana", 10 },
            { "Pet food leftovers", 10 },
            { "Old torn shoelaces", 20 },
            { "Cotton buds", 10 },
            { "Empty tube of toothpaste", 40 },
            { "Empty milk carton", 30 },
            { "Food wrappers", 35 },
            { "Wet wipes", 30 },
            { "Flip-flops", 80 },
            { "Old tent", 120 },
            { "Paper plates", 40 },
            { "Clothing", 40 },
            { "Plastic straw", 55 },
            { "Juice boxes", 40 },
            { "Plastic bags", 30 },
            { "Snack packaging", 30 },
            { "Coffee cups", 40 },
            { "Exhibit map", 20 },
            { "Broken sunglasses", 50 },
            { "Sand toy", 50 },
            { "Beach ball", 45 },
            { "Sunscreen bottles", 40 },
            { "Popped inflatable rafts", 70 },
            { "Abandoned beach towels", 40 },
            { "Cables", 100 },
            { "Polystyrene", 180 },
            { "Metal cleaning acid", 120 },
            { "TV", 200},
            { "Pizza box", 20},
            { "Used tissue", 5},
            { "Food leftovers", 10},
            { "Glass bottles", 95},
            {"ATOMIC BOMB", 5}
        };
    }
}
